# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.


require 'cucumber/rails'

# Ensure database_cleaner-active_record is in Gemfile
require 'database_cleaner/active_record'

# Prevent Capybara from rescuing exceptions (lets failures surface)
ActionController::Base.allow_rescue = false

# Configure DatabaseCleaner
DatabaseCleaner.strategy = :transaction

# Use truncation for JS (if using Selenium/Capybara JS)
Before('@js') do
  DatabaseCleaner.strategy = :truncation
end

Before do
  DatabaseCleaner.start
end

After do
  DatabaseCleaner.clean
end
