# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.


require 'cucumber/rails'

# Include RSpec mocks for Cucumber
require 'rspec/mocks'

World(RSpec::Mocks::ExampleMethods)

Before do
  RSpec::Mocks.setup
end

After do
  begin
    RSpec::Mocks.verify
  ensure
    RSpec::Mocks.teardown
  end
end

# Enable SimpleCov for cucumber runs when requested. This mirrors the RSpec
# configuration and writes a separate resultset so we can collate results
# from RSpec + Cucumber later.
if ENV['CUCUMBER_COVERAGE'] == 'true' || ENV['RAILS_COVERAGE'] == 'true'
  require 'simplecov'
  SimpleCov.command_name 'Cucumber'
  SimpleCov.coverage_dir 'coverage'
  SimpleCov.merge_timeout 3600 # Merge results from the last hour
  SimpleCov.start 'rails' do
    enable_coverage :branch
    add_filter '/features/'
    add_filter '/spec/'
    add_filter '/app/controllers/debug_controller.rb'
  end
end

# Ensure database_cleaner-active_record is in Gemfile
require 'database_cleaner/active_record'

# Prevent Capybara from rescuing exceptions (lets failures surface)
ActionController::Base.allow_rescue = false

# Configure DatabaseCleaner
DatabaseCleaner.strategy = :transaction

# Use truncation for JS (if using Selenium/Capybara JS)
Before('@js') do
  DatabaseCleaner.strategy = :truncation
end

Before do
  DatabaseCleaner.start
  # Cucumber scenarios may stub external services per-scenario; avoid global Spotify/OmniAuth assumptions.
end

# Allow Capybara default host (www.example.com) through Rails host authorization when running
# Cucumber. Rails blocks unknown hosts by default which makes Capybara requests return a host
# authorization page instead of the app HTML.
# Allow common Capybara hosts through Rails host authorization when running Cucumber.
if defined?(Rails) && Rails.respond_to?(:application)
  hosts = Rails.application.config.hosts
  %w[www.example.com 127.0.0.1 localhost].each do |h|
    hosts << h unless hosts.include?(h)
  end
end

# Configure Capybara to bind to localhost explicitly. This helps when running Cucumber in
# CI or where the default host/port differ from Rails' allowed hosts.
if defined?(Capybara)
  Capybara.server_host = '127.0.0.1'
  Capybara.server_port = 9887
  Capybara.app_host = "http://127.0.0.1:9887"
end

After do
  DatabaseCleaner.clean
end

# No Spotify-specific restoration required.
