# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails: config/default.yml

AllCops:
  TargetRubyVersion: 3.4
  Exclude:
    - 'db/schema.rb'
    - 'bin/**'
    - 'node_modules/**'
    - 'tmp/**'
    - 'vendor/**'
Rails:
  Enabled: true
Layout/LineLength:
  Max: 120
